-- Execute this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY,
  name TEXT,
  email TEXT,
  summary TEXT,
  skills TEXT[],
  target_roles TEXT[],
  target_locations TEXT[],
  preferred_job_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Allow public / authenticated access to Profiles
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to profiles" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to profiles" ON public.profiles FOR UPDATE USING (true);


-- 2. Create Tracked Applications Table
CREATE TABLE IF NOT EXISTS public.tracked_applications (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'applied',
  type TEXT DEFAULT 'off-campus',
  applied_date TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Tracked Applications
ALTER TABLE public.tracked_applications ENABLE ROW LEVEL SECURITY;

-- Allow public / authenticated access to Tracked Applications
CREATE POLICY "Allow public read access to tracked_applications" ON public.tracked_applications FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to tracked_applications" ON public.tracked_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to tracked_applications" ON public.tracked_applications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access to tracked_applications" ON public.tracked_applications FOR DELETE USING (true);


-- 3. Create Job Applications Log Table
CREATE TABLE IF NOT EXISTS public.job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  job_id TEXT,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  salary TEXT,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Job Applications
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

-- Allow public / authenticated access to Job Applications
CREATE POLICY "Allow public read access to job_applications" ON public.job_applications FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to job_applications" ON public.job_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to job_applications" ON public.job_applications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access to job_applications" ON public.job_applications FOR DELETE USING (true);
